# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.3.5
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

# System deps
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libyaml-dev \
      pkg-config \
      postgresql-client \
      libpq-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Gems
COPY Gemfile ./
COPY Gemfile.lock* ./
RUN bundle install

# App
COPY . .

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
